@if($level == 1)
    @lang('levels::level.level_one')
@elseif($level == 2)
    @lang('levels::level.level_two')
@elseif($level == 3)
    @lang('levels::level.level_three')
@elseif($level == 4)
    @lang('levels::level.level_four')
@elseif($level == 5)
    @lang('levels::level.level_five')
@elseif($level == 6)
    @lang('levels::level.level_six')
@elseif($level == 7)
    @lang('levels::level.level_seven')
@elseif($level == 8)
    @lang('levels::level.level_eight')
@elseif($level == 9)
    @lang('levels::level.level_nine')
@endif